---
title: "Diario Temtiano edición 29.12.2021"
date: "2021-12-29"
lang: es-es
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
github-repo: temtiteamo/diariotemtiano29122021
description: "Mucho texto acerca de un extenso y diverso tramo de la Historia Temtiana."
header-includes:
  - \usepackage{fancyhdr}
  - \usepackage{lipsum}
  - \pagestyle{plain}
  - \fancyhead[CO,CE]{\thepage}
  - \fancyfoot[LE,RO]{\thepage}
---

# Notas de la edición {.unnumbered}

**Diario Temtiano** edición 29.12.2021

## Novedades en esta edición {.unnumbered}

-   Renombrados los “capítulos” por “libros”. A su vez, los que antes eran “subcapítulos” pasan a ser “capítulos”.

-   Actualizado el apartado “Más sobre Diario Temtiano”. En “Contenido” con las denominaciones actuales de cada componente de la obra, y también para incluir a Titiri dentro de lo que es tratado en ella. En “Agradecimientos” con los gentilicios correspondientes a dicho nombre.

-   Inaugurado un nuevo libro, “Los consolidados pasos del retocado mismo legado (Noveno libro)” con su respectivo texto introductorio.

-   Agregados cuatro capítulos más: “El acto de decisión y continuidad (Noveno libro, capítulo I)”, “Lucidez terminal (Noveno libro, capítulo II)”, “El precario y súper rentable reemplazo (Noveno libro, capítulo III)”, y “El restaurar de la meseta cíclica (Noveno libro, capítulo IV)”, ampliando así el intervalo de tiempo comprendido por la obra hasta el 28 de noviembre de 2021.

# Más sobre Diario Temtiano {.unnumbered}

¿La explicación podría ser peor que la incertidumbre? Intentémoslo!

Antes de continuar con la obra en sí y comenzar a hablar en código, más, aunque ni de cerca todo, sobre Diario Temtiano.

### Contenido {.unnumbered}

Diario Temtiano es una obra literaria que trata especialmente sobre Temti, donde partiendo desde la fecha del 17.01.2021, en orden cronológico se desarrollan interpretaciones de los antecedentes que protagonizaron la Historia Temtiana; sinónimo de lo ocurrido en torno a Temti-Titiri, sus usuarios, su identidad, y lo relacionado a ellos.

Está conformado por un prefacio, una introducción, nueve libros que contienen  un texto preliminar seguido por varios capítulos, y un desenlace.

### Actualizaciones {.unnumbered}

La obra, mediante la publicación de ediciones, las cuales son identificadas con la fecha de las mismas, se actualiza cada tanto para continuar mejorando su contenido. Esto es, corrigiendo errores, incorporando detalles falten y deban ser incluidos, o también reformulando partes que necesiten ser adaptadas, además de también continuar poniéndose al día con los últimos antecedentes.

Salvo que un futuro cambio implique lo contrario, en <https://temtiteamo.github.io/diariotemtiano> siempre se podrá encontrar la edición más reciente y actualizada, por lo que es recomendado en toda ocasión ingresar allí por lo anterior mencionado.

La frecuencia de dichas publicaciones depende mayoritariamente del ritmo al cual se esté desarrollando la Historia Temtiana. Aunque a veces hay excepciones, generalmente Diario Temtiano va unos cuantos días atrasado de lo que esté sucediendo en la actualidad, así que los últimos textos no suelen corresponder inmediatamente a lo más reciente.

### El porqué {.unnumbered}

Como se menciona en el prefacio y en uno de los tantos subcapítulos de Diario Temtiano, el gran disparador para que este surgiera, fue que durante una época bastante particular se sintiera la prolongada ausencia de literatura que interpretara lo que aconteciera en la escena temtiana de ese entonces. Concretamente, esta se padeció notablemente un tanto antes y después del instante que Investigator anunció que de momento no iba a continuar ampliando su obra, Crónicas Temtianas, la cual sí cumplía esa función, mientras que aún seguían ocurriendo una cantidad importante de sucesos y la costumbre de plasmarlos en texto de una manera medianamente ordenada y atractiva se había perdido prácticamente por completo.

Luego de que todo eso se mantuviera por un buen rato, porque el contexto único lo permitiría y ofrecería las condiciones para, pero también gracias a los individuos responsables de su construcción en el pasado y en ese presente, esta historia dentro de la Historia Temtiana comenzó a concretarse...

### Agradecimientos {.unnumbered}

Desde la autoría de la obra, enormes gracias a quienes colaboraron de una forma u otra con Diario Temtiano.

Especiales gracias a los temtiteros, temtineros, temtianos, temteros, timteros, temtistas, temtineitors, titiriteros, titirieros, titirineros, titirianos, titiristas, etc. etc., por contribuir y construir la Historia Temtiana, así como también críticar, sugerir, e interesarse en Diario Temtiano. 

Especiales gracias a Investigator por Crónicas Temtianas y todo lo que estas significan.

Especiales gracias a temtiteamo, A., y al canal oficial de Temti en Telegram por la colaboración extraordinaria en la difusión. 

Especiales gracias a las plataformas a través de las cuales se publicó la obra en sí (Pastebin.com, Rentry.co, Bookdown, Github.com) y a sus responsables por ofrecer las condiciones para que Diario Temtiano pueda estar disponbile en linea.

Especiales gracias a los tantos sitios (Temti.net, Arged.ga, Voxed.club, Tsubit.com, Rouzer.fun, Oldtemti.herokuapp.com, Grupostemti.herokuapp.com), a sus administradores, moderadores, y usuarios, que le permitieron a Diario Temtiano tener un lugar para difundir sus novedades.


